Rathan N Gowda

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('/content/Social_Network_Ads (1).csv')
print(data)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
X=data.iloc[:,[2,3]].values
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
print(data.columns[[2,3]])


Index(['Age', 'EstimatedSalary'], dtype='object')


In [ ]:
Y=data.iloc[:,4].values
print(Y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
print(data.columns[4])

Purchased


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=1/3,random_state=0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)


In [ ]:
#making the confusion matrix
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(X_train,Y_train)  #training the model
print(model)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)


In [ ]:
Y_pred_dec=model.predict(X_test)
Y_pred_dec

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm_dec=confusion_matrix(Y_test,Y_pred_dec)
print(cm_dec)

[[79  6]
 [ 9 40]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Decision tree',accuracy_score(Y_test,Y_pred_dec))

Decision tree 0.8880597014925373


In [ ]:
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression()
modellr.fit(X_train,Y_train)  #training the model
print(modellr)
Y_pred_dec=modellr.predict(X_test)
Y_pred_dec
from sklearn.metrics import confusion_matrix
cmlr_dec=confusion_matrix(Y_test,Y_pred_dec)
print(cmlr_dec)
from sklearn.metrics import accuracy_score
print('Decision tree',accuracy_score(Y_test,Y_pred_dec))

LogisticRegression()
[[79  6]
 [11 38]]
Decision tree 0.8731343283582089


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion='entropy',random_state=0)
RFmodel.fit(X_train,Y_train)
print(RFmodel)
#predictin the test set results
Y_pred_rf=RFmodel.predict(X_test)
from sklearn.metrics import confusion_matrix
cm_rf=confusion_matrix(Y_test,Y_pred_rf)
print(cm_rf)
from sklearn.metrics import accuracy_score
print('Random Forest',accuracy_score(Y_test,Y_pred_rf))

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
[[79  6]
 [ 7 42]]
Random Forest 0.9029850746268657


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)
y_pred_nb = nb.predict(X_test)
cmnb = confusion_matrix(Y_test, y_pred_nb)
print(cmnb)
accuracy_nb = accuracy_score(Y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)

[[80  5]
 [ 8 41]]
Accuracy: 0.9029850746268657


In [ ]:
from sklearn.svm import SVC
model = SVC(kernel='poly',degree=3)
model.fit(X_train,Y_train)
print(model)

SVC(kernel='poly')


In [ ]:
y_pred_svm = svm.predict(X_test)
cmsvm = confusion_matrix(Y_test, y_pred_n)
print(cmsvm)
accuracy_svm = accuracy_score(Y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)

[[80  5]
 [ 8 41]]
Accuracy: 0.9029850746268657


In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(X_train,Y_train)  #training the model
print(model)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
